import Logo from "../../components/atoms/logo"
import Footer from "../../components/layout/footer"
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-4">
        <div className="flex justify-center">
          <Logo />
        </div>
        {children}
        <hr className="my-2" />
        <Footer />
      </body>
    </html>
  )
}
